server:
  port: 8888
spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      routes:
        - id: provider-route
          uri: lb://service-provider
          predicates:
            - Path=/provider/**
          filters:
            - RewritePath=/provider(?<segment>/?.*), $\{segment}
        - id: consumer-route
          uri: lb://service-consumer
          predicates:
            - Path=/consumer/**
          filters:
            - RewritePath=/consumer(?<segment>/?.*), $\{segment}
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848